### ISSUE TITLE
Raspberry Pi 3 B+ specifikacije i sklapanje urađaja

### ISSUE THREAD

**Issue by bramom** [sagittarius-b2/raspberry-pi-projects#2]
Ovo bi bio uvodni projekat, u formi eseja:
- Kratak uvod, o fondaciji i zanimljive činjenice.
- Specifikacija hardvera.
- Kako sklopiti uređaj i uobičajena pitanja ili problemi na koje smo nailazili.
- Najava narednih tekstova, npr. Raspberry Pi i Raspbian kao edukativni računar.

**Comment by dsindjelic** [comment]
Prve dve stavke su urađene, napraviću task za sledeće (sklapanje).

**Comment by bramom** [comment]
OK, zatvaram.
